AWSTemplateFormatVersion: '2010-09-09'
Description: 'Transcribe audio file from an s3 bucket using the TranscribeService

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  BucketNamePrefix:
    Default: vurt-uk
    Type: String
Resources:
  GetTranscriptionFunction:
    Properties:
      CodeUri: s3://vurt-uk/2579e4774af5b0421f4e486b08859579
      Environment:
        Variables:
          RecordingsBucket:
            Ref: SourceRecordingsBucket
      Events:
        GetTranscription:
          Properties:
            Auth:
              Authorizer: NONE
            Method: get
            Path: /recordings/{recordingId}/transcription
          Type: Api
      Handler: app.getTranscription
      Policies:
      - S3ReadPolicy:
          BucketName:
            Fn::Sub: ${BucketNamePrefix}-source-recordings
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ListRecordingsFunction:
    Properties:
      CodeUri: s3://vurt-uk/2579e4774af5b0421f4e486b08859579
      Environment:
        Variables:
          RecordingsBucket:
            Ref: SourceRecordingsBucket
      Events:
        ListRecordings:
          Properties:
            Auth:
              Authorizer: NONE
            Method: get
            Path: /recordings
          Type: Api
      Handler: app.listRecordings
      Policies:
      - S3ReadPolicy:
          BucketName:
            Fn::Sub: ${BucketNamePrefix}-source-recordings
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  SourceRecordingsBucket:
    Properties:
      BucketName:
        Fn::Sub: ${BucketNamePrefix}-source-recordings
    Type: AWS::S3::Bucket
  TranscribeFunction:
    Properties:
      CodeUri: s3://vurt-uk/0a71326a84c86f2bd9e8e4c347361e5f
      Events:
        NewAudioFile:
          Properties:
            Bucket:
              Ref: SourceRecordingsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: recordings/
                - Name: suffix
                  Value: mp3
          Type: S3
      Handler: app.lambdaHandler
      Policies:
      - AmazonTranscribeFullAccess
      - S3CrudPolicy:
          BucketName:
            Fn::Sub: ${BucketNamePrefix}-source-recordings
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
