AWSTemplateFormatVersion: '2010-09-09'
Description: 'Transcribe audio file from an s3 bucket using the TranscribeService

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  BucketNamePrefix:
    Default: vurt-uk
    Type: String
Resources:
  ApiGatewayApi:
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://vurt-uk/cd0b0e0a94c2237926d6689576e832e8
      StageName: Prod
    Type: AWS::Serverless::Api
  GetTranscriptionFunction:
    Properties:
      CodeUri: s3://vurt-uk/651fe391829b4826e9a09985d76405ed
      Environment:
        Variables:
          RecordingsBucket:
            Ref: SourceRecordingsBucket
      Events:
        GetTranscription:
          Properties:
            Method: get
            Path: /recordings/{recordingId}/transcription
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: app.getTranscription
      Policies:
      - S3ReadPolicy:
          BucketName:
            Fn::Sub: ${BucketNamePrefix}-source-recordings
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ListRecordingsFunction:
    Properties:
      CodeUri: s3://vurt-uk/651fe391829b4826e9a09985d76405ed
      Environment:
        Variables:
          RecordingsBucket:
            Ref: SourceRecordingsBucket
      Events:
        ListRecordings:
          Properties:
            Method: get
            Path: /recordings
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: app.listRecordings
      Policies:
      - S3ReadPolicy:
          BucketName:
            Fn::Sub: ${BucketNamePrefix}-source-recordings
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  PreFlightFunction:
    Properties:
      CodeUri: s3://vurt-uk/651fe391829b4826e9a09985d76405ed
      Events:
        GetEvent:
          Properties:
            Method: options
            Path: /recordings
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: app.getPreflightHandler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  SourceRecordingsBucket:
    Properties:
      BucketName:
        Fn::Sub: ${BucketNamePrefix}-source-recordings
    Type: AWS::S3::Bucket
  TranscribeFunction:
    Properties:
      CodeUri: s3://vurt-uk/0a71326a84c86f2bd9e8e4c347361e5f
      Events:
        NewAudioFile:
          Properties:
            Bucket:
              Ref: SourceRecordingsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: recordings/
                - Name: suffix
                  Value: mp3
          Type: S3
      Handler: app.lambdaHandler
      Policies:
      - AmazonTranscribeFullAccess
      - S3CrudPolicy:
          BucketName:
            Fn::Sub: ${BucketNamePrefix}-source-recordings
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
